/*
 * data.js — Nguồn nội dung (định tính) cho trang tổng quan hệ thống HevaSEO.
 * Số liệu đếm được (routes/components/types) nằm ở metrics.js (auto-generated).
 * Trạng thái: 'done' = UI hoàn chỉnh trên mock · 'partial' = cơ bản/đang mở rộng · 'planned' = chờ backend.
 */
window.HEVA = {
  meta: {
    name: 'HevaSEO Platform',
    tagline: 'Nền tảng vận hành dịch vụ SEO end-to-end — từ khách đặt hàng đến đội ngũ giao việc, nghiệm thu & tài chính.',
    phase: 'Phase 0 — Frontend-first trên mock data',
    asOf: '26/06/2026',
    repo: 'monorepo · pnpm workspaces',
  },

  /* ---- "Đây là gì?" — mở đầu cho người chưa biết dự án ---- */
  intro: {
    cards: [
      { icon: 'ph-package', title: 'Sản phẩm là gì?', body: 'Nền tảng vận hành cho một công ty dịch vụ SEO: khách tự đặt dịch vụ, hệ thống giao việc cho đội ngũ, theo dõi giao bài & nghiệm thu, và quản lý tiền — tất cả trong một chỗ.' },
      { icon: 'ph-users', title: 'Phục vụ ai?', body: 'Hai phía: KHÁCH HÀNG (doanh nghiệp cần SEO) tự đặt & theo dõi đơn; và ĐỘI NGŨ nội bộ (staff, manager, admin) nhận và vận hành đơn.' },
      { icon: 'ph-currency-circle-dollar', title: 'Kiếm tiền thế nào?', body: 'Khách nạp credit / thanh toán để mua các gói dịch vụ SEO (audit, content, backlink…). Doanh thu = giá trị đơn; chi phí gồm lương + hoa hồng cho staff.' },
      { icon: 'ph-flask', title: 'Đang ở đâu?', body: 'Hiện toàn bộ GIAO DIỆN đã dựng trên dữ liệu mẫu (mock). Chưa có backend / đăng nhập / thanh toán thật — đó là các phase kế tiếp.' },
    ],
    cast: [
      { role: 'Khách hàng', icon: 'ph-user', color: '#2563eb', line: 'Đặt dịch vụ, theo dõi tiến độ, duyệt bài, quản lý credit.' },
      { role: 'Staff', icon: 'ph-user-focus', color: '#0ea5e9', line: 'Người thực thi: nhận việc, làm, nộp bài — không thấy tiền.' },
      { role: 'Manager', icon: 'ph-user-circle-gear', color: '#a855f7', line: 'Trưởng nhóm vận hành: điều phối & nghiệm thu pod của mình.' },
      { role: 'Admin', icon: 'ph-shield-star', color: '#10b981', line: 'Toàn quyền: đơn, nhân sự, tài chính, catalog, phân tích.' },
    ],
  },

  /* ---- Trạng thái tổng (cho donut "tình hình giao") ---- */
  delivery: [
    { label: 'Giao diện hoàn thiện (mock)', value: 34, color: '#10b981', note: '4 vai trò · ~34 màn hình dựng trên dữ liệu mẫu' },
    { label: 'Đang mở rộng', value: 3, color: '#f59e0b', note: 'Managers v1, một số panel tiếp tục bồi đắp' },
    { label: 'Backend & tích hợp (kế hoạch)', value: 8, color: '#64748b', note: 'Auth, DB/RLS, DB functions, thanh toán — chưa khởi động' },
  ],

  legend: [
    { key: 'done', label: 'UI hoàn chỉnh (mock)', color: '#10b981' },
    { key: 'partial', label: 'Cơ bản / đang mở rộng', color: '#f59e0b' },
    { key: 'planned', label: 'Kế hoạch (chờ backend)', color: '#64748b' },
  ],

  /* ---- Bức tranh kinh doanh (DỮ LIỆU MẪU từ adminMock — minh họa năng lực dashboard) ---- */
  business: {
    note: 'Các con số dưới đây là DỮ LIỆU MẪU (mock) trong adminMock.ts — minh họa những chỉ số dashboard sẽ theo dõi khi backend lên, KHÔNG phải số liệu vận hành thật.',
    kpis: [
      { ic: 'ph-currency-dollar', tone: 'good', v: '$18.6k', l: 'Doanh thu (MTD)', sub: 'Net $18.1k · forecast $24.2k' },
      { ic: 'ph-shopping-bag', tone: 'primary', v: '$86', l: 'Giá trị đơn TB (AOV)', sub: 'ARPU $14.2' },
      { ic: 'ph-users', tone: 'accent', v: '9,820', l: 'MAU', sub: 'DAU 1,240 · WAU 4,380' },
      { ic: 'ph-user-plus', tone: 'primary', v: '902', l: 'User mới (tháng)', sub: 'Giữ chân D30: 41%' },
      { ic: 'ph-package', tone: 'good', v: '105', l: 'Tổng đơn', sub: '6 mới · 11 đang chạy · 3 trễ' },
      { ic: 'ph-lifebuoy', tone: 'warn', v: '5', l: 'Ticket mở', sub: 'Phản hồi đầu TB 1.8h' },
      { ic: 'ph-wallet', tone: 'accent', v: '$2.4k', l: 'Nợ ví khách', sub: 'AR chưa thu + payout chờ' },
      { ic: 'ph-funnel', tone: 'primary', v: '3.1%', l: 'Khách → đơn đầu', sub: 'Funnel: visit → signup → mua' },
    ],
    serviceMix: [
      { service: 'Content', orders: 38, color: '#10b981' },
      { service: 'Keyword', orders: 51, color: '#38bdf8' },
      { service: 'Backlink', orders: 42, color: '#2563eb' },
      { service: 'Audit', orders: 29, color: '#a78bfa' },
      { service: 'Optimization', orders: 24, color: '#f59e0b' },
      { service: 'Indexer', orders: 18, color: '#34d399' },
      { service: 'Web Design', orders: 9, color: '#fb923c' },
    ],
  },

  /* ---- Tech stack ---- */
  tech: [
    { name: 'Next.js 15', note: 'App Router · React Server Components', group: 'Khung app' },
    { name: 'React 19', note: 'UI cho apps/app (portal · staff · admin)', group: 'Khung app' },
    { name: 'Astro', note: 'apps/web — website marketing/bán hàng', group: 'Khung app' },
    { name: 'TypeScript 5.7', note: 'Type-safe toàn bộ; tách tiền khỏi staff bằng type', group: 'Ngôn ngữ' },
    { name: 'Tailwind 3', note: 'Design tokens trong dashboard.css / globals.css', group: 'Giao diện' },
    { name: 'next-themes', note: 'Dark / light mode', group: 'Giao diện' },
    { name: 'react-simple-maps', note: 'Bản đồ phân bố người dùng (Analytics)', group: 'Data-viz' },
    { name: 'Vitest', note: 'Unit test', group: 'Kiểm thử' },
    { name: '@heva/catalog', note: 'Package dùng chung: nguồn dịch vụ & upsell', group: 'Package' },
    { name: '@heva/ui', note: 'Package UI dùng chung', group: 'Package' },
    { name: 'Supabase + Postgres', note: 'KẾ HOẠCH — auth, RLS, DB functions (Phase 1+)', group: 'Backend (kế hoạch)' },
    { name: 'Stripe', note: 'KẾ HOẠCH — quick checkout, nạp credit', group: 'Backend (kế hoạch)' },
  ],

  /* ---- Kiến trúc (sơ đồ khối) ---- */
  architecture: {
    note: 'Monorepo pnpm. Mọi màn hình đọc dữ liệu từ một lớp mock duy nhất; khi backend lên, chỉ thay nguồn dữ liệu, UI giữ nguyên.',
    blocks: [
      { id: 'web', title: 'apps/web', sub: 'Astro · Marketing', desc: 'Trang giới thiệu, blog, bán dịch vụ. Cửa ngõ thu hút khách.', tone: 'accent' },
      { id: 'app', title: 'apps/app', sub: 'Next.js · 4 khu vực', desc: 'Portal khách · Staff · Manager · Admin trong cùng một app.', tone: 'primary' },
      { id: 'catalog', title: '@heva/catalog', sub: 'Package dùng chung', desc: 'Nguồn DUY NHẤT của dịch vụ + upsell cho cả 2 app.', tone: 'good' },
      { id: 'ui', title: '@heva/ui', sub: 'Package dùng chung', desc: 'Thành phần UI tái sử dụng.', tone: 'good' },
      { id: 'mock', title: 'Lớp dữ liệu mock', sub: 'mock · adminMock · staffMock · services', desc: '~82 type. Điểm DUY NHẤT các màn đọc dữ liệu — seam để swap sang DB.', tone: 'warn' },
      { id: 'be', title: 'Backend (kế hoạch)', sub: 'Supabase · Postgres · Stripe', desc: 'Auth, RLS theo capability + tenant, DB functions, thanh toán.', tone: 'muted' },
    ],
  },

  /* ---- 4 vai trò ---- */
  roles: [
    {
      id: 'customer', name: 'Khách hàng', icon: 'ph-user', color: '#2563eb',
      route: 'apps/app/(portal)', count: 9,
      summary: 'Cổng tự phục vụ: duyệt & đặt 7 dịch vụ SEO, theo dõi dự án/đơn, quản lý credit & hóa đơn, mở ticket hỗ trợ.',
      screens: [
        { name: 'Overview', route: '/dashboard', status: 'done',
          desc: 'Tổng quan: hoạt động gần đây, tiến độ đơn, số dư credit, lối tắt đặt dịch vụ.',
          tier1: [
            'Activity feed — sự kiện mới nhất theo thời gian thực: link được index, bài giao, từ khóa +hạng, nạp credit thành công',
            'Credit balance widget — số dư credit (USD) nổi bật với nút nạp nhanh một click',
            'Active orders progress — thanh tiến trình % từng đơn/dự án đang chạy, biết ngay đơn nào gần xong',
            'Quick order shortcuts — lối tắt đặt ngay 7 dịch vụ từ dashboard, không cần vào Browse services',
          ],
          tier2: [
            'Notification badge — đếm thông báo chưa đọc, click trỏ thẳng vào mục liên quan',
            'Empty state onboarding — hướng dẫn đặt dịch vụ đầu tiên khi tài khoản mới',
            'Recent project cards — nhảy nhanh vào project đang hoạt động gần nhất',
          ],
        },
        { name: 'Projects', route: '/projects', status: 'done',
          desc: 'Gom website theo dự án & thư mục lồng nhau (folder cây), mỗi dự án gắn thẻ dịch vụ đang chạy.',
          tier1: [
            'Folder tree lồng nhau — thư mục cha-con vô hạn cấp với màu nhãn tùy chỉnh, breadcrumb điều hướng rõ ràng',
            'Project cards — tên, domain, trạng thái (planned/progress/completed), ghi chú, cập nhật gần nhất',
            'Service status per project — badge plan/run/done cho mỗi dịch vụ đang chạy trong dự án',
            'Lọc theo folder — chỉ hiển thị dự án thuộc thư mục đang chọn, collapse phần còn lại',
          ],
          tier2: [
            'Empty folder CTA — prompt "Thêm dự án đầu tiên" và hướng dẫn khi folder chưa có gì',
            'Project notes — ghi chú tự do: mục tiêu keyword, ghi nhớ vận hành, link tài liệu',
            'Drag-and-drop reorder (planned) — kéo thả đổi vị trí folder/project theo ý muốn',
          ],
        },
        { name: 'Project detail', route: '/projects/[id]', status: 'done',
          desc: 'Chi tiết một dự án: domain, ghi chú, các đơn theo dịch vụ, tiến độ tổng hợp.',
          tier1: [
            'Domain + ghi chú — thông tin cốt lõi: domain đang chạy SEO và ghi chú mục tiêu của dự án',
            'Đơn theo dịch vụ — liệt kê tất cả đơn của dự án, nhóm theo từng loại dịch vụ (content/backlink/keyword...)',
            'Tiến độ tổng hợp — % hoàn thành của từng dịch vụ, nhìn tổng thể dự án đang ở đâu',
          ],
          tier2: [
            'Quick order CTA — đặt thêm dịch vụ cho dự án này ngay trong trang detail',
            'Activity timeline (planned) — lịch sử thay đổi: đơn mới, deliverable mới, ghi chú cập nhật',
            'Domain metrics link (planned) — link nhanh ra GSC/Ahrefs cho domain đang chạy',
          ],
        },
        { name: 'Orders', route: '/orders', status: 'done',
          desc: 'Danh sách đơn theo trạng thái, slide-over chi tiết: brief, deliverable, comment, activity.',
          tier1: [
            'Đơn nhóm 4 trạng thái — planned · in progress · in review · completed (bản rút gọn thân thiện, ẩn chi tiết nội bộ)',
            'Order card — dịch vụ, gói, domain, ETA, staff phụ trách, chi phí, trạng thái thanh toán',
            'Slide-over chi tiết — brief đã gửi, deliverable từng version (file/link), comment thread, activity timeline',
            'Deep link to project — nhảy vào dự án liên quan từ thẻ đơn',
          ],
          tier2: [
            'Approve / Request changes — duyệt deliverable hoặc yêu cầu chỉnh sửa ngay trong slide-over',
            'Comment on deliverable — để lại phản hồi về bài giao (visible to admin/staff)',
            'Filter / search — tìm đơn theo dịch vụ, trạng thái, khoảng ngày',
            'Version history — xem tất cả version deliverable theo thứ tự thời gian',
          ],
        },
        { name: 'Browse services', route: '/services', status: 'done',
          desc: 'Lưới 7 dịch vụ với blurb; dịch vụ chưa mở hiện "coming soon".',
          tier1: [
            'Lưới 7 dịch vụ — icon màu sắc, tên, mô tả ngắn, giá khởi điểm, CTA "Đặt ngay"',
            'Coming soon badge — đánh dấu dịch vụ chưa nhận đơn, disable click để tránh nhầm',
          ],
          tier2: [
            'Hover pricing preview — hiển thị bảng giá sơ bộ khi di chuột vào dịch vụ',
            'Category filter (planned) — lọc theo nhóm: audit / content / backlink / technical',
            'Featured highlight — nổi bật dịch vụ được gợi ý hoặc đang khuyến mãi',
          ],
        },
        { name: 'Service order', route: '/services/[svc]', status: 'done',
          desc: 'Trang đặt từng dịch vụ: gói/giá, brief động theo dịch vụ, upsell, FAQ, pricing theo bulk/usage.',
          tier1: [
            'Package selection — chọn gói hoặc nhóm gói (Backlink: Entity/Pyramid/Guest Post/PR)',
            'Brief form động — field thay đổi theo từng dịch vụ: keyword, domain, ngôn ngữ, tone, anchor text, số bài...',
            'Pricing calculator — tính giá real-time theo 3 mô hình: gói cố định / bulk (per keyword) / usage (per link)',
            'VIP discount -15% — tự động áp dụng và hiển thị số tiền tiết kiệm cho khách VIP',
            'Order confirmation — xác nhận đặt, trừ credit, tạo đơn mới và kích hoạt workflow',
          ],
          tier2: [
            'Upsell add-ons — dịch vụ bổ sung gợi ý ngay tại trang đặt (nguồn @heva/catalog, đồng nhất với website)',
            'What\'s included — danh sách included items có thể expand theo từng gói',
            'Quy trình thực hiện — 3-5 bước mô tả cách dịch vụ hoạt động từ đặt đến nhận bài',
            'FAQ — câu hỏi thường gặp riêng cho từng loại dịch vụ',
            'Bulk tier pricing — bảng giảm theo volume: content từ 10 bài, indexer theo batch URL',
          ],
        },
        { name: 'Credit & Invoices', route: '/credit', status: 'done',
          desc: 'Số dư, lịch sử giao dịch (nạp/đơn), hóa đơn. Ưu đãi VIP -15%.',
          tier1: [
            'Số dư credit USD — hiển thị real-time, đổi màu cảnh báo khi gần hết',
            'Lịch sử giao dịch — top-up (Visa/PayPal) và charge (trừ theo đơn), mới nhất trước',
            'Invoice list — hóa đơn theo trạng thái: issued / processing / paid',
          ],
          tier2: [
            'VIP discount badge — thể hiện ưu đãi thành viên VIP -15% đang áp dụng',
            'Multiple payment methods (planned) — Visa, PayPal, chuyển khoản ngân hàng',
            'Invoice PDF download (planned) — xuất hóa đơn PDF để làm chứng từ kế toán',
            'Balance forecast (planned) — dự báo số dư sau khi các đơn đang chạy hoàn tất',
          ],
        },
        { name: 'Settings', route: '/settings', status: 'done',
          desc: 'Hồ sơ, tài khoản, tùy chọn.',
          tier1: [
            'Personal profile — tên hiển thị, email, avatar, múi giờ',
            'Account info — ngày tham gia (member since), tier hiện tại (new/silver/gold/VIP)',
          ],
          tier2: [
            'Notification preferences — bật/tắt từng loại thông báo email/in-app',
            'Security (planned) — đổi mật khẩu, bật 2FA',
            'Connected domains (planned) — danh sách domain đã gắn vào các dự án',
          ],
        },
        { name: 'Support', route: '/support', status: 'done',
          desc: 'Tạo & theo dõi ticket hỗ trợ.',
          tier1: [
            'Tạo ticket — chọn loại (technical/billing/consultation), mô tả vấn đề, gắn đơn liên quan',
            'Thread hội thoại — toàn bộ trao đổi theo thứ tự thời gian',
            'Trạng thái ticket — open · in-progress · resolved + SLA countdown hiển thị trực quan',
          ],
          tier2: [
            'Priority marking — đánh dấu urgent để xử lý theo SLA 2h thay vì 24h standard',
            'Attachment — đính kèm file/screenshot làm bằng chứng',
            'Re-open ticket — mở lại ticket đã đóng khi vấn đề chưa thực sự giải quyết',
          ],
        },
      ],
      flows: [
        'Đặt hàng: Browse → chọn gói → điền brief (form động theo dịch vụ) → chọn upsell → xác nhận (chưa trừ tiền tới khi confirm).',
        'Theo dõi: đơn chuyển trạng thái, xem deliverable theo version, để lại comment, duyệt/yêu cầu chỉnh.',
        'Tài chính: nạp credit (Stripe/PayPal — kế hoạch), trừ credit khi confirm đơn, nhận hóa đơn.',
      ],
    },
    {
      id: 'staff', name: 'Staff (Nhân sự giao việc)', icon: 'ph-user-focus', color: '#0ea5e9',
      route: 'apps/app/staff', count: 8,
      summary: 'Không gian làm việc của người thực thi: nhận task, làm, nộp deliverable, qua review. Cố tình ẩn mọi thông tin tiền của khách (tách bằng type — leak là lỗi biên dịch).',
      screens: [
        { name: 'My Day', route: '/staff', status: 'done',
          desc: 'Hôm nay làm gì: task ưu tiên, hành động inline (Start/Resume/Submit) ngay trên dòng.',
          tier1: [
            'Focus queue nhóm 3 mức ưu tiên — Overdue (đỏ) · Due today (amber) · This week (mặc định)',
            'Hành động inline — Start / Resume / Submit ngay trên dòng, không cần mở task',
            'Stats bar — Load x/8 · Overdue · Due today · Cleared (tổng kết theo ngày)',
          ],
          tier2: [
            'Keyboard shortcuts — j/k điều hướng · space hành động · / tìm, không rời tay khỏi bàn phím',
            'Click vùng trái mở task — khu vực click riêng để vào task detail đầy đủ',
            'SLA chip — deadline còn bao nhiêu giờ/ngày ngay trên dòng',
            'Task priority badge — màu high/med/low để nhìn nhanh mức độ ưu tiên',
          ],
        },
        { name: 'My Tasks', route: '/staff/tasks', status: 'done',
          desc: 'Bảng kanban theo cột công việc (Assigned → In progress → In review → Changes requested → Delivered).',
          tier1: [
            'Kanban 5 cột — Assigned · In progress · In review · Changes requested · Delivered',
            'Task card — khách, dịch vụ, gói, deadline, SLA chip, trạng thái hiện tại',
          ],
          tier2: [
            'Column count & WIP indicator — số lượng task trong mỗi cột để thấy tắc nghẽn',
            'Filter theo từ khóa/dịch vụ — tìm task trong board',
            'Drag between columns (planned) — kéo thả chuyển trạng thái trực tiếp',
            'Swimlane theo priority (planned) — gom theo mức ưu tiên trong mỗi cột',
          ],
        },
        { name: 'Task detail', route: '/staff/tasks/[id]', status: 'done',
          desc: 'Brief đầy đủ, checklist self-QA tick được, banner feedback khi bị trả lại, timeline activity, due date nổi bật + SLA, phím tắt "s".',
          tier1: [
            'Brief đầy đủ — toàn bộ brief khách gửi từ lúc checkout: tất cả field dịch vụ, ghi chú, yêu cầu đặc biệt',
            'Self-QA checklist — danh sách tiêu chí tick được, đếm tiến độ X/Y trực quan trước khi nộp',
            'Submit deliverable — nộp file hoặc link kèm ghi chú, tạo version mới trong history',
            'Activity timeline — lịch sử từng version: submitted → approved / changes_requested, newest first',
            'Work log (self-note) — nhật ký cá nhân ghi tiến độ từng bước: mốc thời gian tự điền/nhập tay + đính kèm ảnh/video (upload/paste) & link; nhiều note để task nhiều bước không bị quên khi quay lại. Manager & admin xem được, khách KHÔNG thấy',
          ],
          tier2: [
            'Banner changes_requested — amber nổi bật khi bị trả lại: reviewNote, version bị reject, reviewer, thời điểm',
            'Due date nổi bật + SLA chip — đỏ khi quá hạn, đếm ngược theo giờ',
            'Deliverable card tự khóa — khi task đang in-review/delivered/approved, không cho nộp thêm nhầm',
            'Phím "s" shortcut — nhảy thẳng tới ô ghi chú deliverable và focus luôn',
            '2-tier messaging — comment khách-visible vs. internal-only (cờ riêng biệt, staff kiểm soát)',
            'Version diff (planned) — so sánh trực tiếp version trước và version hiện tại',
          ],
        },
        { name: 'Calendar', route: '/staff/calendar', status: 'done',
          desc: 'Lịch deadline các task.',
          tier1: [
            'Lịch deadline task — hiển thị task theo ngày/tuần, thấy khối lượng theo thời gian',
            'Color-coded urgency — đỏ overdue, amber due today, xanh còn thời gian',
          ],
          tier2: [
            'Click ngày — popup danh sách task due ngày đó',
            'Task count badge — số task trên mỗi ô ngày để thấy ngày nào bận',
            'Month/week view toggle — chuyển giữa xem tháng và xem tuần',
          ],
        },
        { name: 'Deliverables', route: '/staff/deliverables', status: 'done',
          desc: 'Lịch sử nộp bài qua mọi task, số vòng rework.',
          tier1: [
            'Lịch sử nộp bài — tất cả deliverable đã nộp qua mọi task, mới nhất trước',
            'Version status — submitted / approved / changes_requested cho từng version',
          ],
          tier2: [
            'Rework count — số vòng bị trả lại (changes_requested rounds) để tự đánh giá chất lượng',
            'Filter theo trạng thái — lọc chỉ xem approved / đang chờ / bị reject',
            'Sort theo task/ngày — sắp xếp linh hoạt theo nhu cầu xem',
          ],
        },
        { name: 'Performance', route: '/staff/performance', status: 'done',
          desc: 'Điểm composite (quality/on-time/throughput), thu nhập riêng (lương + hoa hồng + thưởng) — KHÔNG lộ giá khách.',
          tier1: [
            'Composite score — tổng hợp 3 chiều: quality · on-time · throughput, mỗi chiều có điểm riêng biệt',
            'Thu nhập bản thân — base salary + commission + bonus = take-home (money-safe: không lộ rate ngược ra doanh thu khách)',
          ],
          tier2: [
            'Trend chart — biểu đồ composite qua các tháng, thấy tiến bộ hoặc sụt giảm',
            'Khách đang chăm — danh sách khách money-free (tên/dự án, không lộ giá trị đơn)',
            'Commission detail — chỉ hiện base/commission/bonus, KHÔNG hiện basis/rate để tránh tính ngược',
            'Monthly comparison — so sánh tháng này vs. tháng trước theo từng chiều',
          ],
        },
        { name: 'Notifications', route: '/staff/notifications', status: 'done',
          desc: 'Hộp thông báo: giao việc mới, yêu cầu chỉnh, nhắc deadline, được duyệt.',
          tier1: [
            'Assignment — thông báo nhận việc mới: task, dịch vụ, deadline, khách',
            'Changes requested — thông báo bị trả lại: task nào, ai trả, lúc nào',
            'Reminder — nhắc deadline sắp tới theo ngưỡng (1 ngày, 4 giờ)',
            'Approved — xác nhận bài được duyệt, task done',
          ],
          tier2: [
            'Read/unread state — phân biệt rõ thông báo chưa đọc, badge trên nav',
            'Deep-link tới task — click thông báo nhảy thẳng vào task liên quan',
            'Filter theo loại — chỉ xem assignment, hoặc chỉ xem changes',
            'Mark all as read — xóa badge nhanh khi không cần xem chi tiết',
          ],
        },
        { name: 'Settings', route: '/staff/settings', status: 'done',
          desc: 'Hồ sơ, bật/tắt nhận việc (availability), gửi đơn xin nghỉ (leave).',
          tier1: [
            'Personal profile — tên, avatar, email, thông tin cá nhân',
            'Availability toggle — bật/tắt nhận việc mới (on = sẵn sàng, off = tạm dừng nhận task)',
            'Leave request — gửi đơn xin nghỉ (from/to/reason/days) chờ admin duyệt',
          ],
          tier2: [
            'Skills self-report — khai báo kỹ năng để routing matching tốt hơn',
            'Timezone preference — múi giờ để due date hiển thị đúng giờ địa phương',
            'Leave history — xem lịch sử nghỉ phép đã được duyệt/từ chối',
          ],
        },
      ],
      flows: [
        'Vòng giao việc: nhận task → Start → làm → self-QA checklist → Submit deliverable (version) → Internal review.',
        'Bị trả lại: banner amber hiện reviewNote của reviewer → sửa → nộp version mới.',
        'Bảo mật: StaffTask cố tình BỎ trường tiền ở mức type; chỉ thu nhập của chính staff được hiện (lương/hoa hồng/thưởng), không suy ngược ra doanh thu khách.',
      ],
    },
    {
      id: 'manager', name: 'Manager (Trưởng nhóm ops)', icon: 'ph-user-circle-gear', color: '#a855f7',
      route: 'admin (gated)', count: 1,
      summary: 'Vai trò admin chỉ-vận-hành: dùng chung admin shell nhưng ẨN Finance/payroll/doanh thu. Quản lý pod nhân sự, điều phối, nghiệm thu — không thấy tiền.',
      screens: [
        { name: 'Managers directory', route: '/admin/managers', status: 'partial',
          desc: 'Danh bạ trưởng nhóm (v1): mỗi manager sở hữu một pod staff, kỹ năng, ghi chú điều phối. Roadmap mở rộng tính năng.',
          tier1: [
            'Danh bạ trưởng nhóm — mỗi manager: tên, title, avatar, pod staff phụ trách',
            'Pod summary — danh sách staff trong pod, kỹ năng tổng hợp của nhóm',
          ],
          tier2: [
            'Ghi chú điều phối — notes nội bộ cho từng manager (vd ưu tiên loại việc, lịch làm việc)',
            'Workload pod (planned) — tổng tải công việc pod hiện tại để biết pod nào đang quá tải',
            'Pod-level performance (planned) — điểm composite trung bình của cả pod',
            'Manager assignment editor (planned) — gán/chuyển staff giữa các pod',
          ],
        },
        { name: 'Dùng chung khu Operate/People', route: '/admin/*', status: 'done',
          desc: 'Orders, Assignment, Review, Tickets, Customers, Staff — qua gate quyền theo capability.',
          tier1: [
            'Capability gate OPERATOR — truy cập: Orders, Assignment, Review, Tickets, Customers, Staff',
            'Finance hidden — ẨN toàn bộ: Finance, payroll, doanh thu, giá khách (cùng shell, khác view)',
          ],
          tier2: [
            'Permission-aware nav — nav sidebar chỉ hiển thị mục có quyền theo capability OPERATOR',
            'Audit trail — hành động của manager vẫn ghi vào audit log với actor là manager',
          ],
        },
      ],
      flows: [
        'Phân quyền theo capability (CLIENT / OPERATOR / EXECUTOR), tên vai là cấu hình sản phẩm.',
        'Mỗi staff thuộc một manager (pod): Sofia — pod search & links; Ken — pod content & optimization.',
        'Manager thấy điều phối/nghiệm thu, KHÔNG thấy Finance, payout, revenue.',
      ],
    },
    {
      id: 'admin', name: 'Admin', icon: 'ph-shield-star', color: '#10b981',
      route: 'apps/app/admin', count: 17,
      summary: 'Trung tâm điều hành đầy đủ, chia 4 nhóm: Operate · People · Business · System. Toàn quyền: điều phối đơn, nhân sự, tài chính, catalog, phân tích, nhật ký, cấu hình.',
      groups: [
        { title: 'Operate', items: [
          { name: 'Overview (Command Center)', route: '/admin', status: 'done',
            desc: 'KPI ops, pipeline theo trạng thái, doanh thu 14 ngày, SLA, capacity, "Needs attention".',
            tier1: [
              'OPS KPIs có sparkline — new orders · in_progress · overdue · unassigned, mỗi KPI có mini sparkline 14 ngày',
              'Pipeline 8 stage — count và màu sắc theo từng trạng thái đơn, thấy ngay đơn đang tắc ở đâu',
              'Revenue 14-day chart — doanh thu theo ngày + delta % vs kỳ trước (trend tốt/xấu)',
            ],
            tier2: [
              'SLA on-time % — tỉ lệ đơn và ticket xử lý đúng hạn so với cam kết SLA',
              'Capacity used % — % tải của toàn đội, biết khi nào cần tuyển thêm',
              '"Needs attention" block — đơn trễ, ticket quá SLA, khách VIP cần xử lý ưu tiên',
              'Geo distribution map — phân bố khách theo quốc gia bằng react-simple-maps',
            ],
          },
          { name: 'Orders', route: '/admin/orders', status: 'done',
            desc: 'Explorer toàn bộ đơn: lọc/tìm, 10 trạng thái vòng đời, nguồn (quick/dashboard), giá trị, staff.',
            tier1: [
              'Full order list — tất cả đơn, tìm nhanh theo code/tên khách/dịch vụ/staff',
              '10 lifecycle statuses — hiển thị đầy đủ 10 trạng thái (admin thấy nhiều hơn bản khách 4 trạng thái)',
              'Multi-dimension filter — lọc: status · service · staff · source · tier khách · date range',
            ],
            tier2: [
              'Order source badge — phân biệt quick checkout (1-click) vs. dashboard order (có brief)',
              'Sort by — sắp xếp theo giá trị đơn, deadline, priority',
              'Bulk status transition (planned) — chuyển trạng thái nhiều đơn cùng lúc',
              'Export CSV (planned) — xuất báo cáo đơn theo kỳ',
            ],
          },
          { name: 'Order detail', route: '/admin/orders/[id]', status: 'done',
            desc: 'Chi tiết đơn: brief, gói, included, upsell, bundle, deliverable, chuyển trạng thái.',
            tier1: [
              'Brief + what\'s included — toàn bộ brief khách gửi + danh sách included items theo gói dịch vụ',
              'Assignment — manager-in-charge, staff thực thi, dự án/folder khách, link deep',
              'Deliverable by version — file/link với status, reviewNote, timestamp, comment thread',
              'Status transition — nút chuyển trạng thái đơn theo lifecycle, validate đúng flow',
            ],
            tier2: [
              'Upsell/add-ons panel — add-on đã chọn tại checkout, giá, trạng thái riêng',
              'Bundle display — các đơn đặt cùng session (khách thường mua nhiều dịch vụ cùng lúc)',
              'Internal comment flag — cờ đánh dấu comment chỉ admin/staff thấy, không lộ ra khách',
              'Link to project/folder — nhảy vào project và folder cây của khách',
            ],
          },
          { name: 'Assignment', route: '/admin/assignment', status: 'done',
            desc: 'Điều phối: queue chưa gán, gợi ý theo kỹ năng + tải, rule routing (pin/auto).',
            tier1: [
              'Queue đơn chưa gán — danh sách đơn cần assign, sắp theo priority + age (lâu nhất lên đầu)',
              'Staff scoring — điểm gợi ý mỗi staff = skill match × capacity penalty × round-robin factor',
              'Manual assignment — chọn staff từ dropdown score-sorted, confirm',
            ],
            tier2: [
              'Routing rules — pin (cố định người theo dịch vụ/khách) vs. auto (pool kỹ năng điểm cao)',
              'Rule priority ordering — sắp xếp rule nào áp trước khi nhiều rule cùng match',
              'Capacity penalty — penalize staff đang quá tải để không giao thêm việc',
              'Re-assign — đổi staff cho đơn đã gán khi có lý do (nghỉ phép, overload)',
              'Bulk assign (planned) — gán nhiều đơn cùng lúc theo filter',
            ],
          },
          { name: 'Review', route: '/admin/review', status: 'done',
            desc: 'Nghiệm thu deliverable theo version: approve / request changes theo checklist QA per dịch vụ.',
            tier1: [
              'Deliverable browser — xem file/link theo version mới nhất trước, preview inline nếu có thể',
              'QA checklist per service — danh sách tiêu chí riêng cho từng dịch vụ (content/backlink/audit/keyword...)',
              'Approve / Request changes — duyệt hoặc ghi reviewNote và trả lại staff',
            ],
            tier2: [
              'First-pass approval rate — % deliverable được duyệt ngay lần đầu (KPI chất lượng đội)',
              'Filter theo service/staff — xem deliverable của nhóm hoặc dịch vụ cụ thể',
              'Version comparison (planned) — so sánh trực tiếp version trước và version mới',
              'Batch review (planned) — duyệt nhiều deliverable cùng dịch vụ cùng lúc',
            ],
          },
          { name: 'Tickets', route: '/admin/tickets', status: 'done',
            desc: 'Hỗ trợ đa kênh (portal/WhatsApp/Messenger/email), SLA urgent/standard, macro trả lời nhanh.',
            tier1: [
              'Unified inbox 4 kênh — portal · WhatsApp · Messenger · email, tất cả trong một nơi',
              'SLA enforcement — urgent 2h / standard 24h, countdown timer, cảnh báo đỏ khi sắp hết',
              'Reply thread — hội thoại đa chiều, gắn order, assign to agent, loại ticket',
            ],
            tier2: [
              'Macro (canned reply) — chèn nhanh câu trả lời mẫu có biến (tên khách, mã đơn, link)',
              'Ticket type tagging — phân loại: technical / billing / consultation',
              'Escalation (planned) — leo thang lên cấp cao hơn khi SLA nguy hiểm',
              'Bulk close (planned) — đóng hàng loạt ticket đã resolve',
            ],
          },
        ]},
        { title: 'People', items: [
          { name: 'Customers', route: '/admin/customers', status: 'done',
            desc: 'Danh sách khách: tier (new→VIP theo chi tiêu), shadow/claimed, đơn, chi tiêu, số dư.',
            tier1: [
              'Customer list với tier — new → silver → gold → VIP tự tính theo tổng chi tiêu',
              'Shadow / claimed status — khách tạo tự động bởi system (chưa claim) vs. đã xác nhận tài khoản',
              'Quick stats — số đơn, tổng chi tiêu, số dư ví, ngày hoạt động gần nhất',
            ],
            tier2: [
              'Filter theo tier, status, ngày hoạt động — xem nhóm khách cụ thể',
              'Search theo tên/email/company — tìm nhanh khách',
              'Bulk tag (planned) — gắn nhãn nhiều khách cùng lúc (vd churn-risk)',
              'Export (planned) — xuất danh sách khách theo filter',
            ],
          },
          { name: 'Customer profile', route: '/admin/customers/[id]', status: 'done',
            desc: 'Hồ sơ: liên hệ, dự án/thư mục, sổ credit (ledger), tag, ghi chú tài khoản.',
            tier1: [
              'Contact info — tên, email, timezone, member since, tier hiện tại',
              'Projects & folders — cấu trúc dự án/thư mục của khách này',
              'Credit ledger — toàn bộ lịch sử nạp/trừ credit (append-only, kiểm toán được)',
              'Account notes — ghi chú dùng chung cho mọi admin làm đơn của khách này',
            ],
            tier2: [
              'Tags — nhãn phân loại: VIP, high-priority, churn-risk, trial...',
              'Order history in profile — xem đơn ngay trong hồ sơ không cần ra Orders',
              'Impersonate (planned) — hỗ trợ khách bằng cách xem portal theo góc nhìn của họ',
            ],
          },
          { name: 'Staff roster', route: '/admin/staff', status: 'done',
            desc: 'Đội ngũ: kỹ năng, capacity/openLoad, điểm composite (quality/on-time/throughput).',
            tier1: [
              'Staff list — tên, avatar, kỹ năng (keyword/backlink/content/optimize), trạng thái active',
              'Capacity vs. openLoad — tải tối đa vs. số việc đang mở, thấy ai còn chỗ',
              'Composite score — tổng hợp quality + on-time + throughput cho mỗi người',
            ],
            tier2: [
              'Filter theo kỹ năng — tìm người có kỹ năng cần thiết cho đơn cụ thể',
              'Sort theo composite / tải — ưu tiên người tốt nhất và còn slot',
              'Availability indicator — biết ai đang on/off nhận việc',
              'Quick assign từ roster — gán đơn ngay từ danh sách không cần vào Assignment',
            ],
          },
          { name: 'Staff profile', route: '/admin/staff/[id]', status: 'done',
            desc: 'Hồ sơ nhân sự: kỹ năng, xu hướng, công việc, manager phụ trách.',
            tier1: [
              'Profile + trend — thông tin cá nhân, xu hướng throughput qua các tuần',
              'Current assignments — danh sách đơn đang xử lý của staff này',
              'Manager / pod — trưởng nhóm phụ trách và pod của staff này thuộc',
            ],
            tier2: [
              'Edit skills & capacity — cập nhật kỹ năng và tải tối đa (capacity)',
              'Deliverable history — xem tất cả bài đã nộp, rate approved/rejected',
              'Commission history (planned) — lịch sử hoa hồng từng tháng',
            ],
          },
          { name: 'Leave queue', route: '/admin/staff/leave', status: 'done',
            desc: 'Duyệt/từ chối đơn xin nghỉ của staff.',
            tier1: [
              'Pending leave list — tất cả đơn xin nghỉ đang chờ duyệt',
              'Leave info — from/to, số ngày, lý do, ngày gửi đơn',
              'Approve / Decline — duyệt hoặc từ chối, ghi lý do',
            ],
            tier2: [
              'Impact preview (planned) — xem đơn nào bị ảnh hưởng nếu staff nghỉ những ngày đó',
              'Leave history per staff — xem toàn bộ lịch sử nghỉ phép của một staff',
              'Bulk action (planned) — duyệt/từ chối nhiều đơn cùng lúc',
            ],
          },
          { name: 'Managers', route: '/admin/managers', status: 'partial',
            desc: 'Danh bạ trưởng nhóm + roadmap (xem vai Manager).',
            tier1: [
              'Manager directory — danh bạ trưởng nhóm với pod staff và kỹ năng tổng hợp',
              'Pod staff list — xem ai thuộc pod nào, biết phân bổ nhân sự',
            ],
            tier2: [
              'Coordination notes — ghi chú điều phối nội bộ cho từng manager',
              'Workload per pod (planned) — tải công việc tổng hợp của từng pod',
              'Assign staff to pod (planned) — điều chỉnh cấu trúc pod theo nhu cầu',
            ],
          },
        ]},
        { title: 'Business', items: [
          { name: 'Finance', route: '/admin/finance', status: 'done',
            desc: 'Sổ giao dịch (nạp/đơn/refund/payout/điều chỉnh), hóa đơn AR, payroll, cashflow, nợ ví & AR.',
            tier1: [
              'Transaction ledger — 5 loại: top-up · charge · refund · payout · adjustment, đầy đủ audit trail',
              'AR Invoices — hóa đơn phải thu: paid / due / overdue, theo dõi doanh thu thực tế',
              'Payroll — tính lương mỗi staff: base + commission (rate x billable basis) + bonus = due',
            ],
            tier2: [
              'Cashflow 30-day chart — tiền vào (top-up, charge) vs. tiền ra (payout, refund)',
              'Top-line summary — nợ ví khách chưa thu, payout cần trả, AR tồn đọng',
              'Date range filter — lọc giao dịch theo kỳ báo cáo',
              'Reconcile (planned) — đối soát với Stripe webhook để phát hiện chênh lệch',
              'Export (planned) — xuất báo cáo tài chính theo kỳ',
            ],
          },
          { name: 'Catalog', route: '/admin/catalog', status: 'done',
            desc: 'Quản lý dịch vụ/gói/giá. Roadmap: sửa giá/upsell một nơi → áp dụng mọi nơi.',
            tier1: [
              'Xem toàn bộ 7 dịch vụ — tên, gói, pricing model, giá, upsell đính kèm',
              'Single source of truth — @heva/catalog, mọi thay đổi áp dụng cho cả website bán và portal đặt',
            ],
            tier2: [
              'Edit prices/descriptions (planned) — sửa giá hoặc mô tả một nơi, áp dụng ngay mọi nơi',
              'Add/remove upsells (planned) — quản lý add-on theo từng dịch vụ',
              'Preview trước publish (planned) — xem trước thay đổi trước khi áp dụng thật',
              'Version history (planned) — lịch sử thay đổi giá/gói để kiểm toán',
            ],
          },
          { name: 'Analytics', route: '/admin/analytics', status: 'done',
            desc: 'Doanh thu (gross/net/AOV/ARPU/forecast), service mix, audience (DAU/WAU/MAU), retention, funnel, geo.',
            tier1: [
              'Revenue metrics — gross / net / AOV / ARPU / forecast (dự báo cuối tháng dựa trên xu hướng hiện tại)',
              'Service mix — doanh thu theo từng dịch vụ (số đơn + giá trị), thấy ngay dịch vụ nào sinh tiền nhất',
              'Audience metrics — DAU / WAU / MAU, stickiness (DAU/MAU), new vs. returning users',
            ],
            tier2: [
              'Retention cohort — tỉ lệ khách quay lại theo cohort đăng ký (tháng 1, 2, 3...)',
              'Conversion funnel — visit → signup → first order → repeat order với tỉ lệ mỗi bước',
              'Geo distribution — bản đồ thế giới phân bố khách theo quốc gia (react-simple-maps)',
              'Date range comparison — so sánh kỳ này vs. kỳ trước theo khung thời gian tùy chọn',
            ],
          },
        ]},
        { title: 'System', items: [
          { name: 'Audit log', route: '/admin/audit', status: 'done',
            desc: 'Nhật ký mọi hành động: create/update/transition/assign/destructive/auth — kèm diff & meta.',
            tier1: [
              '6 action categories — create · update · transition · assign · destructive · auth',
              '8 entity types — order / customer / staff / rule / ticket / deliverable / catalog / auth',
              'Field-level diff — thấy chính xác field nào thay đổi, từ giá trị nào sang giá trị nào',
            ],
            tier2: [
              'Actor identification — ai thực hiện: admin tên X / staff / system (webhook tự động)',
              'Filter đa chiều — lọc theo category, entity, actor, date range',
              'Search by entity ID — tìm toàn bộ audit trail của một đơn hoặc khách cụ thể',
              'Meta fields — IP, reason (lý do admin nhập), delta value cho actions phức tạp',
              'Export for compliance (planned) — xuất log theo kỳ phục vụ yêu cầu kiểm toán',
            ],
          },
          { name: 'Settings', route: '/admin/settings', status: 'done',
            desc: 'Cấu hình: business, SLA đơn/ticket, trọng số routing & scoring, email template, integrations, tài khoản admin.',
            tier1: [
              'Business config — tên công ty, email hỗ trợ, địa chỉ, timezone, currency, brand color',
              'SLA configuration — ngưỡng thời gian đơn (high/med/low) và ticket (urgent/standard)',
              'Routing weights — trọng số skill / capacity / round-robin cho scoring khi assign',
              'Scoring weights — trọng số quality / on-time / throughput cho điểm composite staff',
            ],
            tier2: [
              'Email templates — mẫu email với biến động (tên khách, mã đơn, link...) cho từng sự kiện',
              'Integrations — kết nối Stripe / Postmark / Turnstile / Slack với API key',
              'Admin accounts — tạo/quản lý tài khoản Master Admin / Admin',
              '2FA status — trạng thái xác thực 2 yếu tố từng tài khoản admin',
            ],
          },
        ]},
      ],
      flows: [
        'Vòng đơn 10 trạng thái: new → confirmed → assigned → in_progress → internal_review → delivered → changes_requested → approved → completed (· canceled).',
        'Payroll: lương cố định theo vai + hoa hồng (rate × giá trị việc billable) + thưởng admin nhập.',
        'Audit-first: hành động nhạy cảm (refund, impersonate, đổi giá, đổi quyền) đều ghi log có diff.',
      ],
    },
  ],

  /* ---- Data model (thực thể + quan hệ) ---- */
  dataModel: {
    note: 'Toàn bộ trong apps/app/src/data (mock). adminMock là xương sống; staffMock đọc lại từ adminMock và CỐ TÌNH loại bỏ trường tiền ở mức type.',
    entities: [
      { name: 'Order / AdminOrder', file: 'adminMock.ts', fields: 'code, customer, service, pkg, status(10), priority, source, value, staff, deadline', rel: 'thuộc Customer · gán Staff · có nhiều Deliverable' },
      { name: 'Deliverable', file: 'adminMock.ts', fields: 'orderId, version, kind(file/link), status(submitted/approved/changes_requested), reviewNote', rel: 'thuộc Order · do Staff nộp · Admin review' },
      { name: 'Customer', file: 'adminMock.ts', fields: 'company, email, status(shadow/claimed), orders, spend, balance, tier(new→vip)', rel: 'có nhiều Order · có Ledger credit' },
      { name: 'Staff', file: 'adminMock.ts', fields: 'skills[], capacity, openLoad, composite, quality, onTime, throughput, role', rel: 'thuộc Manager (pod) · nhận Order · có Payout' },
      { name: 'Manager', file: 'adminMock.ts', fields: 'title, rank, skills[]', rel: 'sở hữu pod Staff (STAFF_MANAGER)' },
      { name: 'Ticket', file: 'adminMock.ts', fields: 'type, channel(4), status, slaTier, assignee, thread[]', rel: 'thuộc Customer · có thể gắn Order' },
      { name: 'Transaction', file: 'adminMock.ts', fields: 'kind(top_up/charge/refund/payout/adjustment), amount, method, status', rel: 'gắn Customer/Staff/Order' },
      { name: 'Invoice', file: 'adminMock.ts', fields: 'customer, issued, due, amount, status(paid/due/overdue), orderCodes[]', rel: 'gắn Customer + nhiều Order' },
      { name: 'Payout', file: 'adminMock.ts', fields: 'base + commission(rate×basis) + bonus = due', rel: 'tính từ Staff + Order billable' },
      { name: 'AuditEntry', file: 'adminMock.ts', fields: 'actor, entity(8), action, category(6), diff[], meta', rel: 'tham chiếu mọi entity' },
      { name: 'SvcCatalog', file: 'services.ts', fields: 'packages/groups, fields(brief động), bulk/usage pricing, addons, faqs', rel: 'nguồn cho trang đặt dịch vụ + đối chiếu @heva/catalog' },
      { name: 'LeaveRequest', file: 'adminMock.ts', fields: 'staff, from, to, days, reason, status', rel: 'do Staff gửi · Admin duyệt' },
    ],
  },

  /* ---- Roadmap (Phase 0–4, theo spec kiến trúc + CEO/Eng review 26/06) ---- */
  roadmap: [
    { phase: 'Phase 0', title: 'Nền móng', status: 'in-progress', tone: 'warn',
      items: ['Frontend đầy đủ trên mock (ĐANG: ~34 màn, 4 vai trò)', 'tenant_id + RLS scope tenant', 'Balance O(1) + credit_ledger append-only', 'DB functions SECURITY DEFINER (_apply_ledger_entry, create_order, advance_order, cancel_order, topup)', 'Webhook idempotent (stripe_event_id UNIQUE)'] },
    { phase: 'Phase 1', title: 'MVP điều phối', status: 'planned', tone: 'muted',
      items: ['Auth magic link + 3 vai (capability)', 'CRUD đơn qua DB function', 'Phân việc, đổi trạng thái', 'Upload deliverable', 'Notifications + Realtime (RLS-checked)'] },
    { phase: 'Phase 2', title: 'Tiền & nghiệm thu', status: 'planned', tone: 'muted',
      items: ['Credit ledger UI thật', 'Quick checkout Stripe (6 chốt)', 'Approve / Request changes', 'Messaging 2 tầng (staff direct, polling)'] },
    { phase: 'Phase 3', title: 'Vận hành sâu & scale-out', status: 'planned', tone: 'muted',
      items: ['Audit UI thật, workload, SLA', 'Analytics đọc read-replica', 'Reconcile jobs', 'Nâng messages lên realtime', 'Tải thử 10k concurrent'] },
    { phase: 'Phase 4', title: 'Forkability & polish', status: 'planned', tone: 'muted',
      items: ['Trích packages/core sạch (fork SaaS demo)', 'White-label tenant thứ 2', 'Mobile, export, email digest'] },
  ],

  /* ---- Vòng doanh thu tối thiểu (CEO review — phải ship cùng nhau) ---- */
  minLoop: {
    title: 'Vòng doanh thu tối thiểu (ưu tiên product-first)',
    note: 'CEO review 26/06: 8 commit gần nhất toàn admin UI trên mock; outcome thật = khách trả tiền + một vòng order chạy end-to-end. Cần ship cùng nhau:',
    steps: [
      'Supabase thật + auth magic link, 1 tenant HevaSEO',
      'Bảng lõi tối thiểu: profiles, services/packages, orders, tasks, deliverables, credit_ledger, customer_balances',
      'RLS capability + tenant: ẩn tiền khỏi staff · scope assignee · messages · cross-tenant',
      'DB functions: _apply_ledger_entry, create_order, advance_order, topup, cancel_order',
      'Một vòng khách: nạp credit → mua dịch vụ → order(debit) → gán staff → nộp deliverable → khách approve → completed',
      'Swap 1 trang khỏi mock sang data thật (chứng minh seam)',
    ],
  },

  /* ---- Danh mục dịch vụ (catalog — nguồn doanh thu) ---- */
  services: {
    note: 'Catalog dùng chung (@heva/catalog + services.ts) — nguồn DUY NHẤT cho cả website bán hàng và trang đặt trong portal. 7 dịch vụ với 3 mô hình giá: gói cố định, theo số lượng (bulk), và theo dung lượng (usage).',
    items: [
      { name: 'Website Audit', icon: 'ph-stethoscope', model: 'Gói', price: 'từ $19', tiers: 'Basic · Standard · Pro', color: '#a78bfa', desc: 'Crawl toàn site, chấm điểm SEO, lộ trình fix ưu tiên + PDF.' },
      { name: 'Keyword Research', icon: 'ph-tree-structure', model: 'Gói', price: 'từ $19', tiers: 'Basic · Standard · Pro', color: '#38bdf8', desc: 'Cụm từ khóa, volume/độ khó/intent, so sánh đối thủ, roadmap.' },
      { name: 'SEO Content', icon: 'ph-pen-nib', model: 'Bulk / bài', price: 'từ $12/bài', tiers: 'AI (A1000–A3000) · Human (H1000–H3000)', color: '#10b981', desc: '1 bài/từ khóa, on-page + chấm điểm; giảm giá từ 10 bài.' },
      { name: 'Backlinks', icon: 'ph-share-network', model: 'Gói (4 nhóm)', price: 'từ $36', tiers: 'Entity · Pyramid · Guest Post · PR', color: '#2563eb', desc: 'Link an toàn white-hat, kèm Indexer miễn phí + báo cáo từng link.' },
      { name: 'Website Optimization', icon: 'ph-gauge', model: 'Gói', price: 'từ $40', tiers: 'Basic · Standard · Ultra · Custom', color: '#f59e0b', desc: 'Tốc độ, Core Web Vitals, on-page, AI-ready (GEO) + deploy.' },
      { name: 'SEO Web Design', icon: 'ph-palette', model: 'Gói', price: 'từ $79', tiers: 'Landing · Statistic · Blog · E-commerce · Webapp', color: '#fb923c', desc: 'Bản nháp trong 2 ngày, build chuẩn SEO từ ngày đầu.' },
      { name: 'Backlink Indexer', icon: 'ph-magnifying-glass', model: 'Usage / link', price: 'từ $0.004/link', tiers: 'Bậc theo số lượng URL', color: '#34d399', desc: 'Đẩy link vào index Google, báo cáo từng link; free kèm Backlink.' },
    ],
  },

  /* ---- Vòng đời đơn hàng (10 trạng thái) ---- */
  lifecycle: {
    note: 'Mọi đơn đi qua một state machine 10 trạng thái. Khách thấy bản rút gọn; admin/staff thấy đầy đủ. Chuyển trạng thái được validate ở backend (advance_order — kế hoạch).',
    steps: [
      { k: 'new', l: 'Mới', t: 'primary' },
      { k: 'confirmed', l: 'Đã xác nhận', t: 'primary' },
      { k: 'assigned', l: 'Đã giao', t: 'primary' },
      { k: 'in_progress', l: 'Đang làm', t: 'primary' },
      { k: 'internal_review', l: 'Review nội bộ', t: 'accent' },
      { k: 'delivered', l: 'Đã giao bài', t: 'warn' },
      { k: 'changes_requested', l: 'Yêu cầu chỉnh', t: 'warn' },
      { k: 'approved', l: 'Đã duyệt', t: 'good' },
      { k: 'completed', l: 'Hoàn tất', t: 'good' },
      { k: 'canceled', l: 'Đã hủy', t: 'muted' },
    ],
    rules: [
      { icon: 'ph-arrow-u-up-left', color: '#f59e0b', title: 'Khách yêu cầu chỉnh sửa',
        desc: 'Sau khi đơn ở "Đã giao bài" (delivered), khách xem deliverable và có thể yêu cầu chỉnh → đơn về "Yêu cầu chỉnh" (changes_requested), quay lại staff làm version mới. Lặp nhiều vòng tới khi khách hài lòng.' },
      { icon: 'ph-timer', color: '#10b981', title: 'Tự duyệt sau 7 ngày',
        desc: 'Nếu sau khi "Đã giao bài" mà khách KHÔNG review / KHÔNG phản hồi / KHÔNG yêu cầu gì trong vòng 7 ngày, đơn TỰ ĐỘNG chuyển sang "Đã duyệt" (approved) → "Hoàn tất". Tránh đơn treo vô hạn và đảm bảo ghi nhận doanh thu.' },
    ],
  },

  /* ---- Phân quyền: ai thấy gì (RBAC theo capability) ---- */
  rbac: {
    note: 'Phân quyền theo capability (CLIENT / OPERATOR / EXECUTOR), tên vai là cấu hình sản phẩm. Điểm mấu chốt: tiền/giá khách bị ẨN khỏi Staff & Manager ở mức type — leak là lỗi biên dịch.',
    cols: ['Khách', 'Staff', 'Manager', 'Admin'],
    rows: [
      { area: 'Đặt dịch vụ / đơn của mình', v: ['yes', 'no', 'no', 'yes'] },
      { area: 'Việc được giao (task)', v: ['no', 'yes', 'yes', 'yes'] },
      { area: 'Giá khách / doanh thu', v: ['own', 'no', 'no', 'yes'] },
      { area: 'Điều phối & phân việc', v: ['no', 'no', 'yes', 'yes'] },
      { area: 'Nghiệm thu deliverable', v: ['own', 'no', 'yes', 'yes'] },
      { area: 'Tài chính / payroll', v: ['own', 'self', 'no', 'yes'] },
      { area: 'Catalog & giá', v: ['no', 'no', 'no', 'yes'] },
      { area: 'Audit log & cấu hình', v: ['no', 'no', 'no', 'yes'] },
    ],
    legend: { yes: 'Toàn quyền', no: 'Không', own: 'Chỉ của mình', self: 'Chỉ lương của mình' },
  },

  /* ---- Hành trình xuyên vai trò (một đơn đi qua cả 4 vai) ---- */
  journey: {
    note: 'Một đơn hàng đi qua cả 4 vai trò — đây là vòng giá trị end-to-end của hệ thống.',
    steps: [
      { actor: 'Khách hàng', color: '#2563eb', icon: 'ph-shopping-cart', title: 'Đặt đơn', desc: 'Chọn dịch vụ + gói, điền brief, xác nhận → trừ credit.' },
      { actor: 'Admin', color: '#10b981', icon: 'ph-flow-arrow', title: 'Xác nhận & giao', desc: 'Duyệt đơn, gán staff theo kỹ năng + tải (hoặc rule routing).' },
      { actor: 'Staff', color: '#0ea5e9', icon: 'ph-pen-nib', title: 'Thực thi', desc: 'Nhận task, làm, self-QA, nộp deliverable theo version.' },
      { actor: 'Manager / Admin', color: '#a855f7', icon: 'ph-seal-check', title: 'Nghiệm thu', desc: 'Review theo checklist QA: duyệt hoặc trả lại (changes requested).' },
      { actor: 'Khách hàng', color: '#2563eb', icon: 'ph-thumbs-up', title: 'Duyệt bài', desc: 'Khách xem deliverable, approve hoặc yêu cầu chỉnh — tự duyệt sau 7 ngày nếu không phản hồi.' },
      { actor: 'Admin / Finance', color: '#f59e0b', icon: 'ph-wallet', title: 'Ghi nhận', desc: 'Đơn hoàn tất; ghi doanh thu, tính hoa hồng staff.' },
    ],
  },

  /* ---- Bảng thuật ngữ ---- */
  glossary: [
    { term: 'Deliverable', def: 'Sản phẩm bàn giao của một đơn (file hoặc link), nộp theo version.' },
    { term: 'SLA', def: 'Cam kết thời gian phản hồi/hoàn thành (vd ticket urgent 2h, standard 24h).' },
    { term: 'Tier (khách)', def: 'Hạng khách theo tổng chi tiêu: new → silver → gold → VIP.' },
    { term: 'Credit', def: 'Số dư trả trước trong ví khách, dùng để mua dịch vụ.' },
    { term: 'Capacity / openLoad', def: 'Khả năng nhận việc tối đa của staff / số việc đang mở.' },
    { term: 'Composite', def: 'Điểm tổng hợp năng lực staff (quality + on-time + throughput).' },
    { term: 'Routing / Assignment', def: 'Cơ chế gán đơn cho staff theo kỹ năng & tải, hoặc rule cố định (pin).' },
    { term: 'Shadow / Claimed', def: 'Khách tạo tự động (chưa nhận tài khoản) / đã xác nhận sở hữu.' },
    { term: 'Upsell / Add-on', def: 'Dịch vụ bán kèm được gợi ý lúc checkout.' },
    { term: 'RLS', def: 'Row-Level Security — phân quyền truy cập từng dòng dữ liệu ở DB (kế hoạch).' },
    { term: 'Tenant', def: 'Đơn vị tách dữ liệu để white-label/đa khách hàng (mỗi tenant một không gian).' },
    { term: 'Capability', def: 'Mô hình quyền theo năng lực (CLIENT / OPERATOR / EXECUTOR); tên vai là cấu hình.' },
    { term: 'GEO', def: 'Generative Engine Optimization — tối ưu để AI / AI-search trích dẫn website.' },
    { term: 'E-E-A-T', def: 'Experience, Expertise, Authoritativeness, Trust — tiêu chí chất lượng nội dung của Google.' },
    { term: 'DR / DA', def: 'Domain Rating / Authority — điểm uy tín tên miền, dùng khi đánh giá backlink.' },
    { term: 'Mock data', def: 'Dữ liệu mẫu cứng trong code để dựng UI trước khi có backend.' },
    { term: 'Auto-approve (7 ngày)', def: 'Đơn ở trạng thái "Đã giao bài" tự chuyển sang "Đã duyệt" nếu khách không phản hồi/yêu cầu chỉnh trong 7 ngày.' },
  ],
};
